export interface Product {
  id: string;
  name: string;
  price: number;
  originalPrice?: number;
  image: string;
  images: string[];
  category: string;
  brand: string;
  rating: number;
  reviewCount: number;
  description: string;
  colors: string[];
  sizes: string[];
  inStock: boolean;
}

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Premium Wireless Headphones",
    price: 299.99,
    originalPrice: 399.99,
    image: "https://picsum.photos/seed/headphones1/600/600",
    images: ["https://picsum.photos/seed/headphones1/600/600","https://picsum.photos/seed/headphones2/600/600","https://picsum.photos/seed/headphones3/600/600","https://picsum.photos/seed/headphones4/600/600"],
    category: "Electronics",
    brand: "SoundMax",
    rating: 4.8,
    reviewCount: 342,
    description: "Experience crystal-clear audio with our flagship wireless headphones. Featuring active noise cancellation, 30-hour battery life, and premium leather cushions for all-day comfort.",
    colors: ["#1a1a1a","#f5f5f5","#c0392b"],
    sizes: [],
    inStock: true,
  },
  {
    id: "2",
    name: "Minimalist Leather Backpack",
    price: 189.00,
    image: "https://picsum.photos/seed/backpack1/600/600",
    images: ["https://picsum.photos/seed/backpack1/600/600","https://picsum.photos/seed/backpack2/600/600","https://picsum.photos/seed/backpack3/600/600"],
    category: "Accessories",
    brand: "UrbanCarry",
    rating: 4.5,
    reviewCount: 128,
    description: "Crafted from premium full-grain leather, this minimalist backpack combines style with functionality. Features a padded laptop sleeve, multiple compartments, and water-resistant lining.",
    colors: ["#8B4513","#1a1a1a","#2c3e50"],
    sizes: ["Standard","Large"],
    inStock: true,
  },
  {
    id: "3",
    name: "Smart Fitness Watch Pro",
    price: 449.99,
    originalPrice: 549.99,
    image: "https://picsum.photos/seed/watch1/600/600",
    images: ["https://picsum.photos/seed/watch1/600/600","https://picsum.photos/seed/watch2/600/600","https://picsum.photos/seed/watch3/600/600"],
    category: "Electronics",
    brand: "FitTech",
    rating: 4.7,
    reviewCount: 891,
    description: "Advanced fitness tracking with GPS, heart rate monitoring, sleep analysis, and 7-day battery life. Water-resistant up to 50m depth.",
    colors: ["#1a1a1a","#c0c0c0","#4a90d9"],
    sizes: ["40mm","44mm","46mm"],
    inStock: true,
  },
  {
    id: "4",
    name: "Organic Cotton Oversized Tee",
    price: 59.99,
    image: "https://picsum.photos/seed/tee1/600/600",
    images: ["https://picsum.photos/seed/tee1/600/600","https://picsum.photos/seed/tee2/600/600","https://picsum.photos/seed/tee3/600/600"],
    category: "Clothing",
    brand: "EcoWear",
    rating: 4.3,
    reviewCount: 215,
    description: "Made from 100% GOTS-certified organic cotton. Features a relaxed oversized fit, reinforced seams, and a soft brushed interior for ultimate comfort.",
    colors: ["#ffffff","#1a1a1a","#708090","#2c3e50"],
    sizes: ["XS","S","M","L","XL","XXL"],
    inStock: true,
  },
  {
    id: "5",
    name: "Ceramic Pour-Over Coffee Set",
    price: 79.99,
    originalPrice: 99.99,
    image: "https://picsum.photos/seed/coffee1/600/600",
    images: ["https://picsum.photos/seed/coffee1/600/600","https://picsum.photos/seed/coffee2/600/600","https://picsum.photos/seed/coffee3/600/600"],
    category: "Home",
    brand: "BrewCraft",
    rating: 4.9,
    reviewCount: 76,
    description: "Handcrafted ceramic pour-over dripper with matching carafe. Features a spiral rib design for optimal water flow and flavor extraction.",
    colors: ["#ffffff","#1a1a1a","#8B4513"],
    sizes: [],
    inStock: true,
  },
  {
    id: "6",
    name: "Titanium Running Shoes",
    price: 219.00,
    image: "https://picsum.photos/seed/shoes1/600/600",
    images: ["https://picsum.photos/seed/shoes1/600/600","https://picsum.photos/seed/shoes2/600/600","https://picsum.photos/seed/shoes3/600/600","https://picsum.photos/seed/shoes4/600/600"],
    category: "Footwear",
    brand: "RunFast",
    rating: 4.6,
    reviewCount: 445,
    description: "Ultra-lightweight running shoes with responsive foam cushioning and breathable mesh upper. Engineered for speed with a carbon-fiber plate.",
    colors: ["#ffffff","#1a1a1a","#ff4500","#1e90ff"],
    sizes: ["US 7","US 8","US 9","US 10","US 11","US 12"],
    inStock: true,
  },
  {
    id: "7",
    name: "Portable Bluetooth Speaker",
    price: 129.99,
    image: "https://picsum.photos/seed/speaker1/600/600",
    images: ["https://picsum.photos/seed/speaker1/600/600","https://picsum.photos/seed/speaker2/600/600","https://picsum.photos/seed/speaker3/600/600"],
    category: "Electronics",
    brand: "SoundMax",
    rating: 4.4,
    reviewCount: 567,
    description: "360° omnidirectional sound with deep bass and crystal-clear highs. IPX7 waterproof rating, 24-hour playtime, and built-in microphone for calls.",
    colors: ["#1a1a1a","#c0c0c0","#2ecc71"],
    sizes: [],
    inStock: true,
  },
  {
    id: "8",
    name: "Merino Wool Blend Scarf",
    price: 89.99,
    image: "https://picsum.photos/seed/scarf1/600/600",
    images: ["https://picsum.photos/seed/scarf1/600/600","https://picsum.photos/seed/scarf2/600/600","https://picsum.photos/seed/scarf3/600/600"],
    category: "Accessories",
    brand: "WoolCraft",
    rating: 4.7,
    reviewCount: 93,
    description: "Luxuriously soft merino wool blend scarf with classic herringbone pattern. Temperature-regulating properties keep you warm without overheating.",
    colors: ["#8B0000","#1a1a1a","#2c3e50","#c0c0c0"],
    sizes: ["One Size"],
    inStock: true,
  },
  {
    id: "9",
    name: "Mechanical Keyboard RGB",
    price: 159.99,
    originalPrice: 199.99,
    image: "https://picsum.photos/seed/keyboard1/600/600",
    images: ["https://picsum.photos/seed/keyboard1/600/600","https://picsum.photos/seed/keyboard2/600/600","https://picsum.photos/seed/keyboard3/600/600"],
    category: "Electronics",
    brand: "KeyMaster",
    rating: 4.8,
    reviewCount: 724,
    description: "Premium mechanical keyboard with hot-swappable switches, per-key RGB lighting, and aircraft-grade aluminum frame. N-key rollover and USB-C connectivity.",
    colors: ["#1a1a1a","#c0c0c0"],
    sizes: ["60%","75%","TKL","Full"],
    inStock: true,
  },
  {
    id: "10",
    name: "Linen Button-Down Shirt",
    price: 98.00,
    image: "https://picsum.photos/seed/shirt1/600/600",
    images: ["https://picsum.photos/seed/shirt1/600/600","https://picsum.photos/seed/shirt2/600/600","https://picsum.photos/seed/shirt3/600/600"],
    category: "Clothing",
    brand: "BreezyWear",
    rating: 4.5,
    reviewCount: 167,
    description: "Relaxed-fit linen shirt with mother-of-pearl buttons. Pre-washed for softness, it gets better with every wear. Perfect for warm-weather styling.",
    colors: ["#ffffff","#f5deb3","#add8e6","#d3d3d3"],
    sizes: ["XS","S","M","L","XL"],
    inStock: true,
  },
  {
    id: "11",
    name: "Stainless Steel Water Bottle",
    price: 39.99,
    image: "https://picsum.photos/seed/bottle1/600/600",
    images: ["https://picsum.photos/seed/bottle1/600/600","https://picsum.photos/seed/bottle2/600/600","https://picsum.photos/seed/bottle3/600/600"],
    category: "Home",
    brand: "HydroLife",
    rating: 4.6,
    reviewCount: 1203,
    description: "Double-wall vacuum insulated water bottle keeps drinks cold for 24h or hot for 12h. BPA-free, powder-coated finish, and leak-proof lid.",
    colors: ["#1a1a1a","#ffffff","#4a90d9","#2ecc71","#e74c3c"],
    sizes: ["500ml","750ml","1L"],
    inStock: true,
  },
  {
    id: "12",
    name: "Polarized Aviator Sunglasses",
    price: 175.00,
    originalPrice: 220.00,
    image: "https://picsum.photos/seed/sunglasses1/600/600",
    images: ["https://picsum.photos/seed/sunglasses1/600/600","https://picsum.photos/seed/sunglasses2/600/600","https://picsum.photos/seed/sunglasses3/600/600"],
    category: "Accessories",
    brand: "RayLux",
    rating: 4.7,
    reviewCount: 389,
    description: "Classic aviator silhouette with polarized CR-39 lenses and titanium frame. UV400 protection, anti-reflective coating, and adjustable nose pads.",
    colors: ["#c0c0c0","#8B4513","#1a1a1a"],
    sizes: ["Standard","Wide"],
    inStock: true,
  },
];
