import { NextResponse } from "next/server";

// Seed 28 products using the actual products table schema
// Column names: id, name, slug, description, short_description, price,
//               original_price, sku, stock_quantity, stock_status,
//               category_id, brand_id, is_featured, is_trending,
//               is_active, metadata, created_at, updated_at
export async function POST() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceKey) {
    return NextResponse.json({ error: "Server not configured" }, { status: 500 });
  }

  const PRODUCTS = [
    // ── Electronics ──────────────────────────────────────────────────
    {
      name: "AirPods Pro 3rd Gen",
      slug: "airpods-pro-3rd-gen",
      description: "Next-generation active noise cancellation with transparency mode, adaptive audio, and up to 6 hours of listening time. USB-C charging case with built-in speaker and lanyard loop.",
      short_description: "Next-gen ANC earbuds with USB-C",
      price: 249,
      original_price: null,
      sku: "APL-AIRPODS-3",
      stock_quantity: 45,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: true,
      is_trending: true,
      is_active: true,
    },
    {
      name: "MacBook Air M4 15\"",
      slug: "macbook-air-m4-15",
      description: "Supercharged by the M4 chip with a 15-inch Liquid Retina display, up to 18 hours of battery life, and a fanless design. Perfect for work, creativity, and everything in between.",
      short_description: "M4 chip, 15\" Retina, 18hr battery",
      price: 1299,
      original_price: null,
      sku: "APL-MBA-M4-15",
      stock_quantity: 20,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: true,
      is_trending: true,
      is_active: true,
    },
    {
      name: "iPhone 16 Pro Max",
      slug: "iphone-16-pro-max",
      description: "Titanium design with the A18 Pro chip, Camera Control, 48MP Fusion camera, and the longest battery life ever in an iPhone. 6.9\" Super Retina XDR display.",
      short_description: "Titanium, A18 Pro, 48MP camera",
      price: 1199,
      original_price: 1299,
      sku: "APL-IPH-16-PM",
      stock_quantity: 35,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: true,
      is_trending: true,
      is_active: true,
    },
    {
      name: "Samsung Galaxy S25 Ultra",
      slug: "samsung-galaxy-s25-ultra",
      description: "6.8\" QHD+ Dynamic AMOLED 2X display, 200MP camera system, S Pen built in, Snapdragon 8 Elite processor, and Galaxy AI built in. The ultimate Android flagship.",
      short_description: "200MP camera, S Pen, Snapdragon 8 Elite",
      price: 1099,
      original_price: 1199,
      sku: "SAM-S25U",
      stock_quantity: 28,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: true,
      is_trending: false,
      is_active: true,
    },
    {
      name: "Sony WH-1000XM6",
      slug: "sony-wh-1000xm6",
      description: "Industry-leading noise cancellation with 8 microphones, 30-hour battery, hi-res audio certified, speak-to-chat, and multipoint connection. The gold standard in ANC headphones.",
      short_description: "Best-in-class ANC, 30hr battery",
      price: 399,
      original_price: 449,
      sku: "SNY-WH1KM6",
      stock_quantity: 40,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: true,
      is_active: true,
    },
    {
      name: "Apple Watch Ultra 3",
      slug: "apple-watch-ultra-3",
      description: "The most rugged and capable Apple Watch ever. 49mm titanium case, precision dual-frequency GPS, up to 36 hours of battery, and 86-decibel siren.",
      short_description: "49mm titanium, 36hr battery, precision GPS",
      price: 849,
      original_price: null,
      sku: "APL-AWU-3",
      stock_quantity: 18,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: true,
      is_trending: false,
      is_active: true,
    },

    // ── Clothing ─────────────────────────────────────────────────────
    {
      name: "Premium Merino Wool Crew Neck",
      slug: "premium-merino-wool-crew-neck",
      description: "Ultra-soft 100% Australian merino wool in a classic crew neck fit. Temperature-regulating, odor-resistant, and machine washable. Available in 8 colors.",
      short_description: "100% Australian merino, 8 colors",
      price: 128,
      original_price: 160,
      sku: "CLO-MER-WOOL-CN",
      stock_quantity: 60,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: true,
      is_trending: false,
      is_active: true,
    },
    {
      name: "Tailored Slim-Fit Chinos",
      slug: "tailored-slim-fit-chinos",
      description: "Premium cotton twill with just the right amount of stretch. Tailored through the hip and thigh with a narrow leg. Perfect for work or weekend. 6 colors.",
      short_description: "Cotton twill stretch, tailored fit, 6 colors",
      price: 89,
      original_price: null,
      sku: "CLO-SF-CHINO",
      stock_quantity: 80,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: true,
      is_active: true,
    },
    {
      name: "Cashmere Blend Overcoat",
      slug: "cashmere-blend-overcoat",
      description: "Luxurious 80% cashmere, 20% merino wool blend. Double-breasted with horn buttons, fully lined, and cut to hit at the knee. An investment piece.",
      short_description: "80% cashmere, double-breasted, horn buttons",
      price: 595,
      original_price: 750,
      sku: "CLO-CASH-OVER",
      stock_quantity: 15,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: true,
      is_trending: false,
      is_active: true,
    },
    {
      name: "Organic Cotton Oxford Shirt",
      slug: "organic-cotton-oxford-shirt",
      description: "Button-down collar oxford in 100% GOTS-certified organic cotton. Regular fit with a soft, lived-in feel from day one. White, light blue, and sage.",
      short_description: "GOTS-certified organic cotton, button-down",
      price: 75,
      original_price: null,
      sku: "CLO-OXFORD",
      stock_quantity: 90,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: false,
      is_active: true,
    },
    {
      name: "Heavyweight French Terry Hoodie",
      slug: "heavyweight-french-terry-hoodie",
      description: "480gsm French terry loopback cotton. Oversized fit, kangaroo pocket, flat drawstrings, and ribbed cuffs. The perfect layer for any season.",
      short_description: "480gsm French terry, oversized fit",
      price: 110,
      original_price: null,
      sku: "CLO-FT-HOOD",
      stock_quantity: 55,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: true,
      is_active: true,
    },

    // ── Footwear ────────────────────────────────────────────────────
    {
      name: "Suede Chelsea Boot",
      slug: "suede-chelsea-boot",
      description: "Italian suede upper with an elastic gore side panel and rubber lug sole. Goodyear welted construction for resoleability. Available in cognac, midnight, and olive.",
      short_description: "Italian suede, Goodyear welted, lug sole",
      price: 245,
      original_price: null,
      sku: "FTW-CHELSEA-SD",
      stock_quantity: 35,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: true,
      is_trending: false,
      is_active: true,
    },
    {
      name: "Leather Chelsea Boot",
      slug: "leather-chelsea-boot",
      description: "Full-grain calfskin leather with a Blake-stitched construction. Sleek silhouette, Cuban heel, and leather sole with rubber insert. Cognac and black.",
      short_description: "Full-grain calfskin, Blake-stitched, Cuban heel",
      price: 320,
      original_price: 380,
      sku: "FTW-CHELSEA-LTH",
      stock_quantity: 25,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: false,
      is_active: true,
    },
    {
      name: "Canvas Low-Top Sneaker",
      slug: "canvas-low-top-sneaker",
      description: "Organic canvas upper on a classic vulcanized rubber sole. Minimal branding, cushioned insole, and a timeless low profile. Machine washable.",
      short_description: "Organic canvas, vulcanized sole, washable",
      price: 68,
      original_price: null,
      sku: "FTW-CNV-LT",
      stock_quantity: 100,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: true,
      is_active: true,
    },
    {
      name: "Running Shoe — CloudFoam",
      slug: "running-shoe-cloudfoam",
      description: "Lightweight mesh upper with CloudFoam midsole for plush cushioning on every stride. Durable rubber outsole with flex grooves. Great for running or everyday wear.",
      short_description: "Lightweight mesh, CloudFoam cushioning",
      price: 95,
      original_price: null,
      sku: "FTW-RUN-CF",
      stock_quantity: 70,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: false,
      is_active: true,
    },

    // ── Accessories ─────────────────────────────────────────────────
    {
      name: "Leather Card Wallet",
      slug: "leather-card-wallet",
      description: "Vegetable-tanned Italian leather, 8 card slots, 2 bill compartments, and a coin pocket. Slim profile that fits in any pocket. Ages beautifully with use.",
      short_description: "Italian leather, 8 cards, slim profile",
      price: 85,
      original_price: null,
      sku: "ACC-WAL-CARD",
      stock_quantity: 50,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: false,
      is_active: true,
    },
    {
      name: "Cashmere Scarf",
      slug: "cashmere-scarf",
      description: "12-ply Mongolian cashmere, hand-finished fringes. 70cm x 200cm — versatile as a wrap or a shawl. 8 solid colors and 4 seasonal patterns.",
      short_description: "Mongolian cashmere, 70x200cm, 12 colors",
      price: 195,
      original_price: 240,
      sku: "ACC-SCF-CASH",
      stock_quantity: 40,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: false,
      is_active: true,
    },
    {
      name: "Titanium Minimalist Watch",
      slug: "titanium-minimalist-watch",
      description: "Grade 5 titanium case, 39mm, sapphire crystal, quartz movement, 100m water resistance. Swiss-made with interchangeable straps.",
      short_description: "Grade 5 titanium, sapphire crystal, 100m WR",
      price: 485,
      original_price: null,
      sku: "ACC-WCH-TI",
      stock_quantity: 12,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: true,
      is_trending: false,
      is_active: true,
    },
    {
      name: "Leather Tote Bag",
      slug: "leather-tote-bag",
      description: "Full-grain leather tote with hand-stitched handles, magnetic snap closure, and interior zip pocket. Fits a 15\" laptop. Available in tan and black.",
      short_description: "Full-grain leather, fits 15\" laptop, 2 colors",
      price: 245,
      original_price: null,
      sku: "ACC-BAG-TOTE",
      stock_quantity: 30,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: true,
      is_trending: true,
      is_active: true,
    },

    // ── Home & Living ───────────────────────────────────────────────
    {
      name: "Linen Duvet Cover Set",
      slug: "linen-duvet-cover-set",
      description: "Pre-washed 100% European flax linen. OEKO-TEX certified, gets softer with every wash. Includes duvet cover and 2 pillow shams. 8 muted colors.",
      short_description: "European flax linen, OEKO-TEX, 8 colors",
      price: 185,
      original_price: 220,
      sku: "HOM-BED-LIN",
      stock_quantity: 40,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: false,
      is_active: true,
    },
    {
      name: "Hand-Poured Soy Candle",
      slug: "hand-poured-soy-candle",
      description: "100% soy wax, cotton wick, 60+ hour burn time. Scents: Cedar & Sage, Bergamot & Black Tea, Oud & Amber. Amber glass vessel, reusable.",
      short_description: "100% soy, 60+hrs, 3 scents",
      price: 42,
      original_price: null,
      sku: "HOM-CND-SOY",
      stock_quantity: 75,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: true,
      is_active: true,
    },
    {
      name: "Weighted Blanket 7kg",
      slug: "weighted-blanket-7kg",
      description: "Premium glass bead filling in a removable organic cotton cover. The deep pressure stimulation helps reduce stress and improve sleep quality.",
      short_description: "Glass beads, organic cotton cover, 7kg",
      price: 145,
      original_price: null,
      sku: "HOM-BLK-WGT",
      stock_quantity: 30,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: false,
      is_active: true,
    },
    {
      name: "Stainless Tumbler 32oz",
      slug: "stainless-tumbler-32oz",
      description: "Double-wall vacuum insulation keeps drinks cold 24hrs or hot 12hrs. 18/8 stainless, BPA-free lid, fits most cup holders. 5 colors.",
      short_description: "24hr cold / 12hr hot, 18/8 stainless",
      price: 38,
      original_price: null,
      sku: "HOM-CUP-TUM",
      stock_quantity: 120,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: false,
      is_active: true,
    },

    // ── Sports ──────────────────────────────────────────────────────
    {
      name: "Yoga Mat — Natural Rubber",
      slug: "yoga-mat-natural-rubber",
      description: "5mm natural tree rubber with microfibre suede surface. Grippy when wet, eco-friendly, and machine washable. Includes carrying strap.",
      short_description: "5mm natural rubber, grippy when wet",
      price: 85,
      original_price: null,
      sku: "SPT-YGA-MAT",
      stock_quantity: 45,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: false,
      is_active: true,
    },
    {
      name: "Resistance Band Set",
      slug: "resistance-band-set",
      description: "5 levels of resistance from 5 to 50 lbs. Premium latex, non-slip handles, and door anchor included. Perfect for travel or home gym.",
      short_description: "5 levels, 5-50lbs, door anchor included",
      price: 35,
      original_price: null,
      sku: "SPT-RES-BND",
      stock_quantity: 95,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: true,
      is_active: true,
    },
    {
      name: "Insulated Gym Bag",
      slug: "insulated-gym-bag",
      description: "Duffle bag with thermal compartment for wet clothes, ventilated shoe compartment, and laptop sleeve. Water-resistant nylon with YKK zippers.",
      short_description: "Thermal & shoe compartments, laptop sleeve",
      price: 78,
      original_price: null,
      sku: "SPT-GYM-BAG",
      stock_quantity: 50,
      stock_status: "in_stock",
      category_id: "b3eab649-7e26-45f9-9093-daad3cf512c2",
      brand_id: null,
      is_featured: false,
      is_trending: false,
      is_active: true,
    },
  ];

  const results = { created: [] as string[], errors: [] as string[] };

  for (const product of PRODUCTS) {
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    const { is_featured: _f, is_trending: _t, ...rest } = product;

    const res = await fetch(`${supabaseUrl}/rest/v1/products`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: serviceKey,
        Authorization: `Bearer ${serviceKey}`,
        Prefer: "return=representation",
      },
      body: JSON.stringify(rest),
    });

    if (res.ok) {
      const data = await res.json();
      results.created.push(`${product.name} (${data[0]?.id?.slice(0,8)})`);
    } else {
      const err = await res.text();
      results.errors.push(`${product.name}: ${err.slice(0, 120)}`);
    }
  }

  return NextResponse.json(
    { message: `Seeded ${results.created.length} products`, results },
    { status: 201 }
  );
}